<?php
namespace FGS\GestionComptesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieMouvementFinancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementFinancierRepository extends EntityRepository
{
	public function updateMouvementFiancierWithCmfFromList($categorie, $cmfIdList)
	{
		return $this->_em->createQueryBuilder()
			->update('FGSGestionComptesBundle:MouvementFinancier', 'mf')
			->set('mf.categorieMouvementFinancier', ':categorie')
			->where($this->_em->createQueryBuilder()->expr()->in('mf.categorieMouvementFinancier', $cmfIdList))
			->setParameter('categorie', $categorie)
			->getQuery()
			->execute();
	}
}
