<?php
namespace FGS\GestionComptesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieMouvementFinancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementFinancierRepository extends EntityRepository
{
	public function updateMouvementFiancierWithCmfFromList($categorie, $cmfIdList)
	{
		return $this->_em->createQueryBuilder()
			->update('FGSGestionComptesBundle:MouvementFinancier', 'mf')
			->set('mf.categorieMouvementFinancier', ':categorie')
			->where($this->_em->createQueryBuilder()->expr()->in('mf.categorieMouvementFinancier', $cmfIdList))
			->setParameter('categorie', $categorie)
			->getQuery()
			->execute();
	}
	
	public function getMouvementFinancierAndCompteAndUser($id)
	{
		return $this->_em->createQueryBuilder()
			->select('mf','c','u')
			->from('FGSGestionComptesBundle:MouvementFinancier', 'mf')
			->leftJoin('mf.compte', 'c')
			->leftJoin('c.utilisateur', 'u')
			->where('mf.id = :id')
			->setParameter('id', $id)
			->getQuery()
			->getSingleResult();
	}
	
	/*
	public function getAllDistinctYearMonthForCompte($id)
	{
	
		$qb	= $this->createQueryBuilder('mf');
		$qb->select($qb->expr()->substring('mf.date',1,7))
			->distinct('mf.date');

		return $qb->getQuery()->getScalarResult();
	}
	*/
}
